<a href="https://colab.research.google.com/github/sharma1saransh/python/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#numpy is used to create nd arrays where nd stands for n dimensions i.e 1d 2d 3d etc
import numpy as np
lst1=[1,2,3,4]
lst2=[5,6,7,8]
lst3=[20,11,0,1]
arr=np.array([lst1,lst2,lst3])
print(arr)
arr.reshape(4,3)  #reshapes the printed array into the dimensions provided

[[ 1  2  3  4]
 [ 5  6  7  8]
 [20 11  0  1]]


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8, 20],
       [11,  0,  1]])

numpy is faster than tuples and lists



In [ ]:
#using a tuple in numpy
import numpy as np
t1 = (5,6,0,3)
t2 = (3,2,5,6)
t3 = (8,9,4,3)
arr1 = np.array(t1)

arr2 = np.array(t2)

arr3 = np.array(t3)
arr[1:2:3]

array([[5, 6, 7, 8]])

In [48]:
#arranging
import numpy as np
np.arange(2,18).reshape(4,4)

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13],
       [14, 15, 16, 17]])

In [52]:
#random picking of numbers from a given set of numbers or their range
import numpy as np
np.random.randint(0,50,4).reshape(2,2) #0 - start ; 50 - termination ; 4 - random 4 numbers


array([[26, 39],
       [ 9, 42]])